"""add live and pre match bet media

Revision ID: 1af00e4c1641
Revises: 92bfad2b00d5
Create Date: 2026-09-13 18:42:50.219979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1af00e4c1641'
down_revision: Union[str, Sequence[str], None] = '92bfad2b00d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vip_menu_settings', sa.Column('live_bets_media_file_id', sa.String(length=512), nullable=True))
    op.add_column('vip_menu_settings', sa.Column('live_bets_media_type', sa.String(length=32), nullable=True))
    op.add_column('vip_menu_settings', sa.Column('pre_match_bets_media_file_id', sa.String(length=512), nullable=True))
    op.add_column('vip_menu_settings', sa.Column('pre_match_bets_media_type', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vip_menu_settings', 'pre_match_bets_media_type')
    op.drop_column('vip_menu_settings', 'pre_match_bets_media_file_id')
    op.drop_column('vip_menu_settings', 'live_bets_media_type')
    op.drop_column('vip_menu_settings', 'live_bets_media_file_id')
    # ### end Alembic commands ###
