"""add user onboarding

Revision ID: 3120b0a92f25
Revises: aa00e9077804
Create Date: 2026-09-13 01:48:39.979227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3120b0a92f25'
down_revision: Union[str, Sequence[str], None] = 'aa00e9077804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_onboarding',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('language_selected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vip_category_id', sa.BigInteger(), nullable=True),
    sa.Column('category_selected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contact_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vip_access_granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_onboarding')
    # ### end Alembic commands ###
