"""add timezone to bot admins

Revision ID: 4a73dff28a9e
Revises: 39a9a2561414
Create Date: 2026-09-13 22:31:25.690822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a73dff28a9e'
down_revision: Union[str, Sequence[str], None] = '39a9a2561414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_admins', sa.Column('timezone', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_admins', 'timezone')
    # ### end Alembic commands ###
