"""add content screen settings

Revision ID: 6c69afbbb6a4
Revises: 4a73dff28a9e
Create Date: 2026-09-14 00:32:19.950686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c69afbbb6a4'
down_revision: Union[str, Sequence[str], None] = '4a73dff28a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_screen_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('screen_key', sa.String(length=64), nullable=False),
    sa.Column('heading', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('footer', sa.Text(), nullable=True),
    sa.Column('media_file_id', sa.String(length=512), nullable=True),
    sa.Column('media_type', sa.String(length=20), nullable=True),
    sa.Column('registration_url', sa.String(length=1024), nullable=True),
    sa.Column('promo_code', sa.String(length=255), nullable=True),
    sa.Column('support_username', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_screen_settings_screen_key'), 'content_screen_settings', ['screen_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_screen_settings_screen_key'), table_name='content_screen_settings')
    op.drop_table('content_screen_settings')
    # ### end Alembic commands ###
