"""add vip support username

Revision ID: 911554f2c85e
Revises: a7b1606a2e31
Create Date: 2026-09-13 15:48:25.509332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '911554f2c85e'
down_revision: Union[str, Sequence[str], None] = 'a7b1606a2e31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vip_categories', sa.Column('support_username', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vip_categories', 'support_username')
    # ### end Alembic commands ###
