"""add live and pre match bet settings

Revision ID: 92bfad2b00d5
Revises: 76564da9ae59
Create Date: 2026-09-13 18:21:38.880777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92bfad2b00d5'
down_revision: Union[str, Sequence[str], None] = '76564da9ae59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vip_menu_settings', sa.Column('live_bets_heading', sa.String(length=255), nullable=True))
    op.add_column('vip_menu_settings', sa.Column('live_bets_info', sa.String(length=4000), nullable=True))
    op.add_column('vip_menu_settings', sa.Column('pre_match_bets_heading', sa.String(length=255), nullable=True))
    op.add_column('vip_menu_settings', sa.Column('pre_match_bets_info', sa.String(length=4000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vip_menu_settings', 'pre_match_bets_info')
    op.drop_column('vip_menu_settings', 'pre_match_bets_heading')
    op.drop_column('vip_menu_settings', 'live_bets_info')
    op.drop_column('vip_menu_settings', 'live_bets_heading')
    # ### end Alembic commands ###
