"""add vip category media and registration settings

Revision ID: a7b1606a2e31
Revises: e5827f25d624
Create Date: 2026-09-13 15:22:58.060422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7b1606a2e31'
down_revision: Union[str, Sequence[str], None] = 'e5827f25d624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vip_categories', sa.Column('registration_url', sa.String(length=2048), nullable=True))
    op.add_column('vip_categories', sa.Column('promo_code', sa.String(length=128), nullable=True))
    op.add_column('vip_categories', sa.Column('media_file_id', sa.String(length=512), nullable=True))
    op.add_column('vip_categories', sa.Column('media_type', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vip_categories', 'media_type')
    op.drop_column('vip_categories', 'media_file_id')
    op.drop_column('vip_categories', 'promo_code')
    op.drop_column('vip_categories', 'registration_url')
    # ### end Alembic commands ###
