"""add membership gate tables

Revision ID: aa00e9077804
Revises: 454fdf2d440b
Create Date: 2026-09-13 01:05:08.482640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa00e9077804'
down_revision: Union[str, Sequence[str], None] = '454fdf2d440b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('invite_url', sa.String(length=512), nullable=True),
    sa.Column('is_required', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='100', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_telegram_chat_id'), 'channels', ['telegram_chat_id'], unique=True)
    op.create_table('channel_memberships',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_status', sa.String(length=32), nullable=False),
    sa.Column('is_satisfied', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel_id', name='uq_channel_memberships_user_channel')
    )
    op.create_index(op.f('ix_channel_memberships_channel_id'), 'channel_memberships', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_memberships_user_id'), 'channel_memberships', ['user_id'], unique=False)
    op.create_table('membership_checks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_status', sa.String(length=32), nullable=True),
    sa.Column('is_satisfied', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), server_default='telegram_api', nullable=False),
    sa.Column('error', sa.String(length=512), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membership_checks_channel_id'), 'membership_checks', ['channel_id'], unique=False)
    op.create_index(op.f('ix_membership_checks_checked_at'), 'membership_checks', ['checked_at'], unique=False)
    op.create_index(op.f('ix_membership_checks_user_id'), 'membership_checks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_membership_checks_user_id'), table_name='membership_checks')
    op.drop_index(op.f('ix_membership_checks_checked_at'), table_name='membership_checks')
    op.drop_index(op.f('ix_membership_checks_channel_id'), table_name='membership_checks')
    op.drop_table('membership_checks')
    op.drop_index(op.f('ix_channel_memberships_user_id'), table_name='channel_memberships')
    op.drop_index(op.f('ix_channel_memberships_channel_id'), table_name='channel_memberships')
    op.drop_table('channel_memberships')
    op.drop_index(op.f('ix_channels_telegram_chat_id'), table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
