"""add referral system

Revision ID: c0af9cd609ab
Revises: 6c69afbbb6a4
Create Date: 2026-09-14 01:07:00.460247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0af9cd609ab'
down_revision: Union[str, Sequence[str], None] = '6c69afbbb6a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_program_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commission_percent', sa.Integer(), server_default='30', nullable=False),
    sa.Column('vip_link', sa.String(length=1024), nullable=True),
    sa.Column('promo_code', sa.String(length=255), nullable=True),
    sa.Column('claim_username', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_referrals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('referral_code', sa.String(length=64), nullable=False),
    sa.Column('referred_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('referred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referred_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_referrals_referral_code'), 'user_referrals', ['referral_code'], unique=True)
    op.create_index(op.f('ix_user_referrals_referred_by_user_id'), 'user_referrals', ['referred_by_user_id'], unique=False)
    op.create_index(op.f('ix_user_referrals_user_id'), 'user_referrals', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_referrals_user_id'), table_name='user_referrals')
    op.drop_index(op.f('ix_user_referrals_referred_by_user_id'), table_name='user_referrals')
    op.drop_index(op.f('ix_user_referrals_referral_code'), table_name='user_referrals')
    op.drop_table('user_referrals')
    op.drop_table('referral_program_settings')
    # ### end Alembic commands ###
