"""add vip category info

Revision ID: c1c3d4452505
Revises: 911554f2c85e
Create Date: 2026-09-13 16:09:14.230185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1c3d4452505'
down_revision: Union[str, Sequence[str], None] = '911554f2c85e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vip_categories', sa.Column('vip_info', sa.String(length=4000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vip_categories', 'vip_info')
    # ### end Alembic commands ###
