"""add daily picks

Revision ID: e5827f25d624
Revises: 2aa3bd958159
Create Date: 2026-09-13 04:02:20.472418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5827f25d624'
down_revision: Union[str, Sequence[str], None] = '2aa3bd958159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_picks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sport', sa.String(length=64), nullable=False),
    sa.Column('event_title', sa.String(length=255), nullable=False),
    sa.Column('selection', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('odds', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_picks_is_published'), 'daily_picks', ['is_published'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_picks_is_published'), table_name='daily_picks')
    op.drop_table('daily_picks')
    # ### end Alembic commands ###
